---
- name: Build Device Configurations
  gather_facts: false
  hosts: all
  connection: network_cli

  tasks:

    - name: set current time
      set_fact:
        start_time: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
      delegate_to: localhost

    - name: Create a directory for config files
      file:
        path: "{{ playbook_dir }}/{{ start_time }}-configs"
        state: directory
      delegate_to: localhost

    - name: Generate device config files
      template:
        src: base.j2
        dest: "{{ playbook_dir }}/{{ start_time }}-configs/{{ inventory_hostname }}.cfg"
      ignore_errors: true

    - name: Send configs
      ios_config:
        src: "{{ playbook_dir }}/{{ start_time }}-configs/{{ inventory_hostname }}.cfg"
